### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by dontboyle** [hyurl/structured-clone#2]
Error:

**vendor.js:76199 ERROR Error: Uncaught (in promise): ReferenceError: exports is not defined
ReferenceError: exports is not defined**

Resolve, may need to include **_commonjs_** library! or have it as a dependency from what i can tell thats a no-no in angular world though, so you need an angular version?

**Comment by hyurl** [comment]
You need to configure your tsconfig.json webpack.config.js file to support commonjs modules instead.

**Comment by dontboyle** [comment]
Yep thanks that did it! - also happy thanksgiving!
